# Generated by Django 4.0.2 on 2022-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_alter_pontoturisticos_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisticos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
