# Generated by Django 4.0.2 on 2022-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontoturisticos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
