# Generated by Django 4.0.2 on 2022-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontoturisticos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisticos',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
