# Generated by Django 4.0.2 on 2022-02-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontoturisticos_enderecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisticos',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
